In [1]:
import pandas as pd

In [138]:
test = pd.read_csv('breast_normal.csv',header=None)

In [139]:
len(test)

8630

In [140]:
#0 and 1 a bit weeird

In [141]:
test[0].value_counts()

TCGA-3C-AALI-01A-11D-A41F-09    8070
TCGA-3C-AAAU-01A-11D-A41F-09     560
Name: 0, dtype: int64

In [17]:

import multiprocessing as mp
print("Number of processors: ", mp.cpu_count())

Number of processors:  8

In [142]:
test2 = pd.read_csv('breast_tumor.csv',header=None)

In [143]:
test2[1].map(len).value_counts()

100    8622
Name: 1, dtype: int64

In [144]:
test[1].map(len).value_counts()

100    8630
Name: 1, dtype: int64

In [145]:
X = pd.DataFrame({'normal':test[1],'tumor':test2[1]})

In [146]:
X.head()

,normal,tumor
0,CACATGTCCTCGGTGCTTGATGTTACACTCCTGGTTGGAGATGACG...,CACATGTCCTCGGTGCTTGATGTTACACTCCTAGTTGGAGATGACG...
1,CACCAACCTCACAGGCCCCCACAGGGGCCAACAGTCCCTCAGTGCA...,CACCAACCTCACAGGCCCCCACAGGGGCCAACAGTCCCTCAGTGCA...
2,CGCTCTCCCGCACATGTCCTCGGTGCTTGATGTTACACTCCTGGTT...,CGCTCTCCCGCACATGTCCTCGGTGCTTGATGTTACACTCCTAGTT...
3,CTCCCACACATGTCCTCGGTGCTTGATGTTACACTCCTGGTTGGAG...,CTCCCACACATGTCCTCGGTGCTTGATGTTACACTCCTAGTTGGAG...
4,AGGCCCCCACAGGGGCCAACAGTCCCTCAGTGCACATCTCGCTCTC...,AGGCCCCCACAGGGGCCAACAGTCCCTCAGTGCACATCTCGCTCTC...

In [147]:
X[X['normal'] == X['tumor']]

Empty DataFrame
Columns: [normal, tumor]
Index: []

In [113]:
X.loc[8628,'normal']

'AGGGGCAGTCGGGCCAGACTTGTGTCCAGCCACTGGAACCCCTCTCTGCGTATGGCCAGCGCCTCTGGCCTGAGTTGACGGAGCTCTTCCTGTGGCCAGA'

In [114]:
X.loc[8628,'tumor']

'AGGGGCAGTCGGGCCAGACTTGTGTCCAGCCACTGGAACCCCTCTCTGCGTATGGCCAGCGCCTCTGGCCTGAGTTGACGGAGCTCTTCCTGTGGCCAGA'

In [148]:
X.tail(10)

,normal,tumor
8620,GGAACCCCTCTCTGCGTATGGCCAGCGCCTCTGGCCTGAGTTGACG...,CGGGCCAGACTTGTGTCCAGCCACTGGAACCCCTCTCTGCGTATGG...
8621,TCTGCGGGGCTGGGGAGGGGCAGTCGGGCCAGACTTGTGTCCAGCC...,GCCTCTGGCCTCAGTTGACGGAGCTCTTCCTGTGGCCAGACATCTA...
8622,AGGGGCAGTCGGGCCAGACTTGTGTCCAGCCACTGGAACCCCTCTC...,NaN
8623,CTCTGCGGGGCTGGGGAGGGGCAGTCGGGCCAGACTTGTGTCCAGC...,NaN
8624,CAGCCACTGGAACCCCTCTCTGCGTATGGCCAGCGCCTCTGGCCTG...,NaN
8625,ACCCCTCTCTGCGTATGGCCAGCGCCTCTGGCCTGAGTTGACGGAG...,NaN
8626,GGGGCTGGGGAGGGGCAGTCGGGCCAGACTTGTGTCCAGCCACTGG...,NaN
8627,GCCAGCGCCTCTGGCCTGAGTTGACGGAGCTCTTCCTGTGGCCAGA...,NaN
8628,CGGGCCAGACTTGTGTCCAGCCACTGGAACCCCTCTCTGCGTATGG...,NaN
8629,GCCTCTGGCCTGAGTTGACGGAGCTCTTCCTGTGGCCAGACATCTA...,NaN

In [150]:
X.loc[8628,'normal']==X.loc[8620,'tumor']

False

In [165]:
from collections import defaultdict

In [151]:
import pandas as pd
import os

In [152]:
os.chdir("/Users/beth/Documents/SNV project")

In [153]:
gnomad_files = !find . -name "gnomad.exomes.r2*" #filtered with bcf tools for all above .0001 prob

In [154]:
[i[2:] for i in gnomad_files]

['gnomad.exomes.r2.1.1.sites.19.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.2.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.16.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.12.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.6.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.9.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.5.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.11.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.20.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.X.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.15.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.1.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.8.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.22.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.7.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.13.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.17.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.3.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.18.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.14.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.Y.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.21.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.10.liftover_grch38.vcf.bgz',
 'gnomad.exomes.r2.1.1.sites.4.liftover_grch38.vcf.bgz']

In [155]:
current_file = pd.read_csv('gnomad.exomes.r2.1.1.sites.4.liftover_grch38.vcf.bgz', sep=" ", header=None)

In [158]:
current_file[50:100]

       0       1       2     3         4
50  chr4   86205       G     C  0.001582
51  chr4   86208       A     G  0.011017
52  chr4   86210       G    GC  0.998912
53  chr4   86212       C    CG  0.026316
54  chr4   86296       C     G  0.001116
55  chr4   86907       A     G  0.005655
56  chr4   86908       C     T  0.228531
57  chr4   86946       A     G  0.003104
58  chr4   86996       C     A  0.001201
59  chr4   87223       T     C  0.185441
60  chr4   87244       T     G  0.021425
61  chr4   87416       C  CTGT  0.011194
62  chr4   87417       A     G  0.018519
63  chr4   87418       C     G  0.063830
64  chr4   87422       C    CA  0.198182
65  chr4   87422       C     T  0.012727
66  chr4   87423       G    GA  0.999530
67  chr4  160916       G     A  0.003245
68  chr4  160981       T     C  0.001901
69  chr4  161104       A     G  0.003064
70  chr4  161105       A     C  0.003052
71  chr4  161163  AAAGAT     A  0.003485
72  chr4  161220       T     A  0.001868
73  chr4  161575       C     A  0.003058
74  chr4  161618       C     G  0.001575
75  chr4  161621       A     T  0.007784
76  chr4  161834       T     C  0.002409
77  chr4  161865       C     G  0.008352
78  chr4  161885       T     A  0.003063
79  chr4  161898       A     G  0.001910
80  chr4  161923       A     G  0.196838
81  chr4  271152       A     G  0.243933
82  chr4  271406       A     C  0.001518
83  chr4  271439       G     C  0.001831
84  chr4  271663       G     C  0.001083
85  chr4  271758       A     G  0.017035
86  chr4  271874       T     A  0.004163
87  chr4  271954       G     A  0.001038
88  chr4  272166       T     C  0.001453
89  chr4  272335       C     T  0.029087
90  chr4  272382       G     A  0.008964
91  chr4  272675       G     A  0.004410
92  chr4  295424       T     C  0.010199
93  chr4  295462       G     A  0.003450
94  chr4  295483       C     T  0.034475
95  chr4  296009       T     C  0.001078
96  chr4  296046       C     T  0.001081
97  chr4  296088       G     T  0.030648
98  chr4  305292       C     G  0.001072
99  chr4  337951       G     T  0.141112

In [159]:
current_file.loc[current_file[3].apply(len) > 1, 2] = "-"
current_file.loc[current_file[3].apply(len) > 1, 3] = current_file[3].str.slice(start=1)

In [161]:
current_file.loc[current_file[2].apply(len) > 1, 2] = current_file[2].str.slice(start=1)
current_file.loc[current_file[2].apply(len) > 1, 3] = "-"

In [162]:
current_file[50:100]

       0       1      2    3         4
50  chr4   86205      G    C  0.001582
51  chr4   86208      A    G  0.011017
52  chr4   86210      -    C  0.998912
53  chr4   86212      -    G  0.026316
54  chr4   86296      C    G  0.001116
55  chr4   86907      A    G  0.005655
56  chr4   86908      C    T  0.228531
57  chr4   86946      A    G  0.003104
58  chr4   86996      C    A  0.001201
59  chr4   87223      T    C  0.185441
60  chr4   87244      T    G  0.021425
61  chr4   87416      -  TGT  0.011194
62  chr4   87417      A    G  0.018519
63  chr4   87418      C    G  0.063830
64  chr4   87422      -    A  0.198182
65  chr4   87422      C    T  0.012727
66  chr4   87423      -    A  0.999530
67  chr4  160916      G    A  0.003245
68  chr4  160981      T    C  0.001901
69  chr4  161104      A    G  0.003064
70  chr4  161105      A    C  0.003052
71  chr4  161163  AAGAT    -  0.003485
72  chr4  161220      T    A  0.001868
73  chr4  161575      C    A  0.003058
74  chr4  161618      C    G  0.001575
75  chr4  161621      A    T  0.007784
76  chr4  161834      T    C  0.002409
77  chr4  161865      C    G  0.008352
78  chr4  161885      T    A  0.003063
79  chr4  161898      A    G  0.001910
80  chr4  161923      A    G  0.196838
81  chr4  271152      A    G  0.243933
82  chr4  271406      A    C  0.001518
83  chr4  271439      G    C  0.001831
84  chr4  271663      G    C  0.001083
85  chr4  271758      A    G  0.017035
86  chr4  271874      T    A  0.004163
87  chr4  271954      G    A  0.001038
88  chr4  272166      T    C  0.001453
89  chr4  272335      C    T  0.029087
90  chr4  272382      G    A  0.008964
91  chr4  272675      G    A  0.004410
92  chr4  295424      T    C  0.010199
93  chr4  295462      G    A  0.003450
94  chr4  295483      C    T  0.034475
95  chr4  296009      T    C  0.001078
96  chr4  296046      C    T  0.001081
97  chr4  296088      G    T  0.030648
98  chr4  305292      C    G  0.001072
99  chr4  337951      G    T  0.141112

In [166]:
gnomad_dict = defaultdict(list)

for i in gnomad_files:
    file_name = i[2:]
    current_file = pd.read_csv(file_name, sep=" ", header=None)
    
    #change insertion to the same format as TCGA MAF ("-" "ATG" where "A" is not part of ref)
    current_file.loc[current_file[3].apply(len) > 1, 2] = "-"
    current_file.loc[current_file[3].apply(len) > 1, 3] = current_file[3].str.slice(start=1)
    
    #change deletion to the same format as TCGA MAF ("ATG" "-")
    current_file.loc[current_file[2].apply(len) > 1, 2] = current_file[2].str.slice(start=1)
    current_file.loc[current_file[2].apply(len) > 1, 3] = "-"

    for i in range(len(current_file)):
        gnomad_dict[current_file.loc[i,0]].append([current_file.loc[i,1], current_file.loc[i,2], current_file.loc[i,3], current_file.loc[i, 4]])

In [168]:
import pickle

In [169]:
with open('gnomad_dictionary_2.pickle', 'wb') as write_file:
    pickle.dump(gnomad_dict, write_file)

In [170]:
current_file[4].min()

0.0010007